name: Autoupdate

on:
  schedule:
    - cron: "7 * * * *"
  workflow_dispatch:

jobs:
  update-tap:
    runs-on: ubuntu-latest
    steps:
      - name: Update Homebrew Formulae
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: "${{ secrets.ACCESS_TOKEN }}"
          tap: bowtie-json-schema/homebrew-tap
          force: false
          livecheck: true
